CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50),
    email varchar(50)
);

CREATE TABLE IF NOT EXISTS items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(50),
  description varchar(200),
  available bool,
  owner_id bigint,
  FOREIGN KEY (owner_id) REFERENCES users (id)
);